version: '3'
services:
  auth-microservice:
    container_name: auth-microservice
    ports:
      - "3000:3000"
    build: ./auth
    working_dir: /auth_microservice/
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@users_db/auth
    depends_on:
      - users_db
    networks:
      - auth-network
      - app-network
    volumes:
      - ./auth/:/auth_microservice

  users_db:
    container_name: users_db
    image:
      postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - '5432:5432'
    volumes:
      - ./auth/:/db/
    networks:
      - auth-network

  
networks:
  auth-network:
    driver: bridge
  app-network:
    driver: bridge